runtime: nodejs18  # masih didukung static handlers
instance_class: F1

handlers:
  - url: /(.*\.(css|js|png|jpg|ico|json|svg|woff2?))
    static_files: dist/\1
    upload: dist/(.*\.(css|js|png|jpg|ico|json|svg|woff2?))
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
