steps:
  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "${_ENV}", "BE/.env"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/tcc-be-task7", "."]
    dir: "BE" 
  
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/tcc-be-task7"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "tcc-be-task7",
        "--image", "gcr.io/$PROJECT_ID/tcc-be-task7",
        "--port", "5000",
        "--region", "us-central1",
        "--allow-unauthenticated"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
